# Generated by Django 4.2.7 on 2023-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangdong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guname', models.CharField(max_length=100)),
                ('eng', models.CharField(max_length=20)),
                ('lowerEng', models.CharField(max_length=20)),
            ],
        ),
    ]
